### ISSUE TITLE
Are you still alive?

### ISSUE THREAD

**Issue by wmertens** [ryanmcgrath/wrench-js#108]
This looks like an interesting project but no commits for well over a year now…

**Comment by ryanmcgrath** [comment]
I'm still alive, yes, but I figured people would kind of get the hint that there's no changes going on here. There are a plethora of better options for handling this stuff. I keep it around because according to npm it's still in use, but I wouldn't at all recommend anybody continue using it.

**Comment by wmertens** [comment]
Actually, any hints for good other libraries? I only know of q-io.

On Sat, Nov 14, 2015, 3:29 PM Ryan McGrath <notifications@github.com> wrote:

> Closed #108 <https://github.com/ryanmcgrath/wrench-js/issues/108>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ryanmcgrath/wrench-js/issues/108#event-464506373>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by ryanmcgrath** [comment]
@wmertens try https://github.com/jprichardson/node-fs-extra ?
