### ISSUE TITLE
copyDirRecursive doesnot preserve "execute" permission

### ISSUE THREAD

**Issue by Michenux** [ryanmcgrath/wrench-js#92]
Source files with execute permission lost the execute permission.
The target files can not be executed anymore.

Source: -rwxr-xr-x
Target: -rw-r--r--

**Comment by nicka** [comment]
Any news on this?

**Comment by ryanmcgrath** [comment]
@nicka I deprecated the lib this past weekend. No updates forthcoming, sadly.

**Comment by nicka** [comment]
@ryanmcgrath :ok_hand:
